theme: jekyll-theme-minimal
title: lipu lipamanka
description: lipamanaka's website, shared by lipamanka and a few other people
image: https://cdn.discordapp.com/attachments/938446775545651200/1014367624991359006/unknown.png

defaults:
  - scope:
      path: ""
    values:
      layout: "nasin"